export interface Property {
  id: string;
  title?: string;
  name?: string;
  location?: string;
  address?: string;
  price?: number | string;
  rent?: number | string;
  cost?: number | string;
  images?: string[];
  image?: string;
  bedrooms?: number;
  beds?: number;
  bathrooms?: number;
  baths?: number;
  area?: string | number;
  sqft?: string | number;
  units?: string;
  type?: string;
  listingType?: string;
  propertyType?: string;
  status?: string;
  priceUnit?: string;
  price_unit?: string;
  propertyCategory?: string;
  category?: string;
  sellerId?: string;
  ownerId?: string;
  userId?: string;
  contactName?: string;
  sellerName?: string;
  createdAt?: { seconds: number; nanoseconds: number } | null;
  description?: string;
  areaUnit?: string;
  area_unit?: string;
  phone?: string;
  contact?: string;
  videoUrl?: string;
  totalFloors?: number;
  floorNumber?: number;
  furnishingStatus?: string;
  features?: string[];
  balconies?: string | number;
  otherRooms?: string[];
  coveredParking?: string | number;
  openParking?: string | number;
  availabilityStatus?: string;
  ageOfProperty?: string;
  facing?: string;
  overlooking?: string[];
  waterSource?: string[];
  flooring?: string;
  powerBackup?: string;
  facingRoadWidth?: string | number;
  facingRoadUnit?: string;
  possessionBy?: string;
  ownership?: string;
  allInclusivePrice?: boolean;
  taxExcluded?: boolean;
  priceNegotiable?: boolean;
  uniqueDescription?: string;
  floorPlan?: string;
  viewCount?: number;
  developer?: string;
  amenities?: string[];
  lat?: number | null;
  lng?: number | null;
  plotLength?: string | number;
  plotBreadth?: string | number;
  floorsAllowed?: string | number;
  boundaryWall?: string;
  openSides?: string | number;
  anyConstruction?: string;
  builderFloorType?: "Single Floor" | "Duplex" | "Triplex";
  plotArea?: string | number;
  OwnerName?: string;
  size?: string | number;
  project?: string;
  ageOfConstruction?: string;
  floor?: string;
  furnished?: string;
  availableFrom?: string;
  preferredTenants?: string[];
  userType?: "Owner" | "Agent" | "Builder";
  constructionStatus?: string;
  postedBy?: string;
}
