export interface Property {
  id: string;
  title?: string;
  name?: string;
  location?: string;
  address?: string;
  price?: number | string;
  rent?: number | string;
  cost?: number | string;
  images?: string[];
  image?: string;
  bedrooms?: number;
  beds?: number;
  bathrooms?: number;
  baths?: number;
  area?: string | number;
  sqft?: string | number;
  units?: string;
  type?: string;
  listingType?: string;
  propertyType?: string;
  status?: string;
  priceUnit?: string;
  price_unit?: string;
  propertyCategory?: string;
  category?: string;
  sellerId?: string;
  ownerId?: string;
  userId?: string;
  contactName?: string;
  sellerName?: string;
  createdAt?: { seconds: number; nanoseconds: number } | null;
  description?: string;
  areaUnit?: string;
  area_unit?: string;
  phone?: string;
  contact?: string;
  videoUrl?: string;
  totalFloors?: number;
  floorNumber?: number;
  furnishingStatus?: string;
  features?: string[];
  balconies?: string | number;
  builtUpArea?: string | number;
  superBuiltUpArea?: string | number;
  otherRooms?: string[];
  coveredParking?: string | number;
  openParking?: string | number;
  availabilityStatus?: string;
  ageOfProperty?: string;
  facing?: string;
  overlooking?: string[];
  waterSource?: string[];
  flooring?: string;
  powerBackup?: string;
  facingRoadWidth?: string | number;
  facingRoadUnit?: string;
  possessionBy?: string;
  ownership?: string;
  pricePerSqFt?: number | string;
  allInclusivePrice?: boolean;
  taxExcluded?: boolean;
  priceNegotiable?: boolean;
  uniqueDescription?: string;
  floorPlan?: string;
}
